# Generated by Django 6.0.2 on 2026-03-04 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
                ('stage', models.CharField()),
                ('phone1', models.IntegerField(verbose_name='&[+998][-]{1-9}(2)[-]{1-9}(3)[-]{1-9}(2)[-]{1-9}(2)$')),
                ('phone2', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('body', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('applicant', models.CharField()),
                ('phone1', models.IntegerField()),
                ('phone2', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('qabul_qilingan', 'qabul_qilingan'), ('organili_chiqilmoqda', 'organili_chiqilmoqda'), ('rad_etilgan', 'rad_etilgan'), ('hal_qilingan', 'hal_qilingan')], default='qabul_qilingan')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.category')),
            ],
        ),
    ]
