# Generated by Django 6.0.2 on 2026-03-10 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone1',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message='Raqam xato namuna: +998934001949', regex='^[+]998[0-9]{9}$')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone2',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Raqam xato namuna: +998934001949', regex='^[+]998[0-9]{9}$')]),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone1',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message='Raqam xato namuna: +998934001949', regex='^[+]998[0-9]{9}$')]),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone2',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Raqam xato namuna: +998934001949', regex='^[+]998[0-9]{9}$')]),
        ),
        migrations.AlterField(
            model_name='worker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
