# Generated by Django 6.0.2 on 2026-03-10 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_application_name_alter_application_phone1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phone1',
            field=models.CharField(validators=[django.core.validators.RegexValidator(message='Raqam xato namuna: +998934001949', regex='^[+]998[0-9]{9}$')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone2',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Raqam xato namuna: +998934001949', regex='^[+]998[0-9]{9}$')]),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone1',
            field=models.CharField(validators=[django.core.validators.RegexValidator(message='Raqam xato namuna: +998934001949', regex='^[+]998[0-9]{9}$')]),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone2',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Raqam xato namuna: +998934001949', regex='^[+]998[0-9]{9}$')]),
        ),
    ]
