# Generated by Django 6.0.2 on 2026-04-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_application_phone1_alter_application_phone2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='habits name')),
                ('cost', models.PositiveIntegerField(verbose_name='cost')),
                ('frequency', models.PositiveIntegerField(default=1, verbose_name='bir kunda qancha olasiz')),
                ('period', models.CharField(choices=[('oy', 'month'), ('hafta', 'week'), ('yil', 'year')], verbose_name='period')),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='category',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
