# Generated by Django 6.0.2 on 2026-05-01 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_habits_remove_application_category_delete_worker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habits',
            name='since',
            field=models.DateField(default=datetime.date(2026, 5, 1), verbose_name='nechta kun oldin boshlangan'),
        ),
    ]
