# Generated by Django 6.0.2 on 2026-05-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_habits_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='period',
            field=models.CharField(choices=[('oy', 'month'), ('hafta', 'week'), ('yil', 'year'), ('total', 'total')], verbose_name='period'),
        ),
    ]
