# Generated by Django 6.0.2 on 2026-05-07 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_habits_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='since',
            field=models.DateField(default=datetime.date(2026, 5, 7), verbose_name='nechta kun oldin boshlangan'),
        ),
    ]
